version: "3.8"
services:
    api:
        build:
          context: ./API
          dockerfile: Dockerfile
        environment:
            - NODE_ENV=Production
        restart: always
        container_name: api
        env_file:
            - ./API/.env
        depends_on:
            - mongo
            - rabbit
        ports: 
            - ${SERVER_PORT}:${SERVER_PORT}
            - 9229:9229
        volumes:
            - ./API/dist:/app/dist
            - ./API/package.json:/app/package.json
        working_dir: /app
        command: "npm start"
        logging: 
            driver: "json-file"
            options:
              max-size: "10m"
              max-file: "5"

    worker:
        build:
          context: ./Worker
          dockerfile: Dockerfile
        restart: always
        container_name: worker
        environment:
            AMQP_CONNECTIONSTRING: amqp://${AMQP_USER}:${AMQP_PASS}@${AMQP_HOST}:${AMQP_PORT}
            MONGOCONNECTION: mongodb://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?authSource=admin   
            DATABASENAME: ${DB_DATABASE}
        depends_on:
            - mongo
            - rabbit
        logging:
            driver: "json-file"
            options:
              max-size: "10m"
              max-file: "5"

    front-end:
        build:
          context: ./Front-End
          dockerfile: Dockerfile
        restart: always
        container_name: front-end
        ports:
            - 4200:80
        logging:
            driver: "json-file"
            options:
              max-size: "10m"
              max-file: "5"
    
    mongo:
        image: mongo:latest
        restart: always
        env_file:
            - ./API/.env
        container_name: mongo
        ports: 
            - ${DB_PORT}:27017
        environment:
            MONGO_INITDB_DATABASE: ${DB_DATABASE}          
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}         
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    
    rabbit:
        image: "rabbitmq:3.9-management-alpine"
        restart: always
        env_file:
            - ./API/.env
        container_name: rabbit
        hostname: rabbit
        labels:
            NAME: "rabbitmq"
        ports:
            - ${AMQP_PORT}:${AMQP_PORT}
            - 15672:15672
        volumes:
            - ./config/rabbit.conf:/etc/rabbitmq/rabbitmq.conf